// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC00-G7AsrH67Ld3gVSTbG1PvSV-Jg7rDI',
    appId: '1:889968355663:web:4366196f3e35b48569fd3a',
    messagingSenderId: '889968355663',
    projectId: 'kairos-3d873',
    authDomain: 'kairos-3d873.firebaseapp.com',
    storageBucket: 'kairos-3d873.firebasestorage.app',
    measurementId: 'G-2X9HXFB3K8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBXtU1lxBt96VRd28XgT9Nq3rjseBB6Xw',
    appId: '1:889968355663:android:298412f174215bee69fd3a',
    messagingSenderId: '889968355663',
    projectId: 'kairos-3d873',
    storageBucket: 'kairos-3d873.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkVHpAXZkZ4G0-6Kfg93nw9fRqMso13yw',
    appId: '1:889968355663:ios:4525b80728e85e4d69fd3a',
    messagingSenderId: '889968355663',
    projectId: 'kairos-3d873',
    storageBucket: 'kairos-3d873.firebasestorage.app',
    iosClientId: '889968355663-f7si4m8mcraenomv9ne80rrk8jraja0l.apps.googleusercontent.com',
    iosBundleId: 'com.kairos.app',
  );
}
