/// A curated list of major cities for the World Clock "add city" picker —
/// the full IANA tz database (~400 entries) includes many obscure
/// identifiers that would make searching tedious, so this sticks to cities
/// a general audience would actually look for.
const worldCities = <(String name, String timezoneId)>[
  ('Tokyo', 'Asia/Tokyo'),
  ('Seoul', 'Asia/Seoul'),
  ('Beijing', 'Asia/Shanghai'),
  ('Shanghai', 'Asia/Shanghai'),
  ('Hong Kong', 'Asia/Hong_Kong'),
  ('Taipei', 'Asia/Taipei'),
  ('Singapore', 'Asia/Singapore'),
  ('Bangkok', 'Asia/Bangkok'),
  ('Jakarta', 'Asia/Jakarta'),
  ('Manila', 'Asia/Manila'),
  ('Kuala Lumpur', 'Asia/Kuala_Lumpur'),
  ('Ho Chi Minh City', 'Asia/Ho_Chi_Minh'),
  ('New Delhi', 'Asia/Kolkata'),
  ('Mumbai', 'Asia/Kolkata'),
  ('Dhaka', 'Asia/Dhaka'),
  ('Karachi', 'Asia/Karachi'),
  ('Dubai', 'Asia/Dubai'),
  ('Tehran', 'Asia/Tehran'),
  ('Istanbul', 'Europe/Istanbul'),
  ('Moscow', 'Europe/Moscow'),
  ('Athens', 'Europe/Athens'),
  ('Helsinki', 'Europe/Helsinki'),
  ('Cairo', 'Africa/Cairo'),
  ('Johannesburg', 'Africa/Johannesburg'),
  ('Nairobi', 'Africa/Nairobi'),
  ('Lagos', 'Africa/Lagos'),
  ('Rome', 'Europe/Rome'),
  ('Paris', 'Europe/Paris'),
  ('Berlin', 'Europe/Berlin'),
  ('Madrid', 'Europe/Madrid'),
  ('Amsterdam', 'Europe/Amsterdam'),
  ('Zurich', 'Europe/Zurich'),
  ('London', 'Europe/London'),
  ('Lisbon', 'Europe/Lisbon'),
  ('Dublin', 'Europe/Dublin'),
  ('Reykjavik', 'Atlantic/Reykjavik'),
  ('Sao Paulo', 'America/Sao_Paulo'),
  ('Buenos Aires', 'America/Argentina/Buenos_Aires'),
  ('Mexico City', 'America/Mexico_City'),
  ('Bogota', 'America/Bogota'),
  ('New York', 'America/New_York'),
  ('Toronto', 'America/Toronto'),
  ('Chicago', 'America/Chicago'),
  ('Denver', 'America/Denver'),
  ('Phoenix', 'America/Phoenix'),
  ('Los Angeles', 'America/Los_Angeles'),
  ('Vancouver', 'America/Vancouver'),
  ('Anchorage', 'America/Anchorage'),
  ('Honolulu', 'Pacific/Honolulu'),
  ('Auckland', 'Pacific/Auckland'),
  ('Sydney', 'Australia/Sydney'),
  ('Melbourne', 'Australia/Melbourne'),
  ('Brisbane', 'Australia/Brisbane'),
  ('Perth', 'Australia/Perth'),
  ('UTC', 'UTC'),
];
